name: 'Google Cloud IaC Create Resources'

defaults:
  run:
    shell: bash
    working-directory: iac

on:
  push:
    paths:
      - 'iac/**'
      - '.github/workflows/infrastructure-apply.yaml'

jobs:
  setup:
    name: 'Setup GCP and Terraform'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      gcp-cred-path: ${{steps.auth-gcp.outputs.credentials_file_path}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth GCP Service Account
        id: auth-gcp
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/7578655339/locations/global/workloadIdentityPools/cicd-pool/providers/cicd-provider'
          service_account:  'tpch-dbgen-gcs@tpch-dbgen-367914.iam.gserviceaccount.com'

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform-version: 1.1.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve